# Generated by Django 4.1.5 on 2023-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_comentario_usuario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicado_comentario',
            field=models.BooleanField(default=False, verbose_name='Comentário publicado'),
        ),
    ]
